{"ast":null,"code":"/**\n * Copyright (c) 2014-present, Facebook, Inc.\n *\n * This source code is licensed under the MIT license found in the\n * LICENSE file in the root directory of this source tree.\n */var runtime=function(exports){\"use strict\";var Op=Object.prototype;var hasOwn=Op.hasOwnProperty;var undefined;// More compressible than void 0.\nvar $Symbol=typeof Symbol===\"function\"?Symbol:{};var iteratorSymbol=$Symbol.iterator||\"@@iterator\";var asyncIteratorSymbol=$Symbol.asyncIterator||\"@@asyncIterator\";var toStringTagSymbol=$Symbol.toStringTag||\"@@toStringTag\";function define(obj,key,value){Object.defineProperty(obj,key,{value:value,enumerable:true,configurable:true,writable:true});return obj[key];}try{// IE 8 has a broken Object.defineProperty that only works on DOM objects.\ndefine({},\"\");}catch(err){define=function define(obj,key,value){return obj[key]=value;};}function wrap(innerFn,outerFn,self,tryLocsList){// If outerFn provided and outerFn.prototype is a Generator, then outerFn.prototype instanceof Generator.\nvar protoGenerator=outerFn&&outerFn.prototype instanceof Generator?outerFn:Generator;var generator=Object.create(protoGenerator.prototype);var context=new Context(tryLocsList||[]);// The ._invoke method unifies the implementations of the .next,\n// .throw, and .return methods.\ngenerator._invoke=makeInvokeMethod(innerFn,self,context);return generator;}exports.wrap=wrap;// Try/catch helper to minimize deoptimizations. Returns a completion\n// record like context.tryEntries[i].completion. This interface could\n// have been (and was previously) designed to take a closure to be\n// invoked without arguments, but in all the cases we care about we\n// already have an existing method we want to call, so there's no need\n// to create a new function object. We can even get away with assuming\n// the method takes exactly one argument, since that happens to be true\n// in every case, so we don't have to touch the arguments object. The\n// only additional allocation required is the completion record, which\n// has a stable shape and so hopefully should be cheap to allocate.\nfunction tryCatch(fn,obj,arg){try{return{type:\"normal\",arg:fn.call(obj,arg)};}catch(err){return{type:\"throw\",arg:err};}}var GenStateSuspendedStart=\"suspendedStart\";var GenStateSuspendedYield=\"suspendedYield\";var GenStateExecuting=\"executing\";var GenStateCompleted=\"completed\";// Returning this object from the innerFn has the same effect as\n// breaking out of the dispatch switch statement.\nvar ContinueSentinel={};// Dummy constructor functions that we use as the .constructor and\n// .constructor.prototype properties for functions that return Generator\n// objects. For full spec compliance, you may wish to configure your\n// minifier not to mangle the names of these two functions.\nfunction Generator(){}function GeneratorFunction(){}function GeneratorFunctionPrototype(){}// This is a polyfill for %IteratorPrototype% for environments that\n// don't natively support it.\nvar IteratorPrototype={};define(IteratorPrototype,iteratorSymbol,function(){return this;});var getProto=Object.getPrototypeOf;var NativeIteratorPrototype=getProto&&getProto(getProto(values([])));if(NativeIteratorPrototype&&NativeIteratorPrototype!==Op&&hasOwn.call(NativeIteratorPrototype,iteratorSymbol)){// This environment has a native %IteratorPrototype%; use it instead\n// of the polyfill.\nIteratorPrototype=NativeIteratorPrototype;}var Gp=GeneratorFunctionPrototype.prototype=Generator.prototype=Object.create(IteratorPrototype);GeneratorFunction.prototype=GeneratorFunctionPrototype;define(Gp,\"constructor\",GeneratorFunctionPrototype);define(GeneratorFunctionPrototype,\"constructor\",GeneratorFunction);GeneratorFunction.displayName=define(GeneratorFunctionPrototype,toStringTagSymbol,\"GeneratorFunction\");// Helper for defining the .next, .throw, and .return methods of the\n// Iterator interface in terms of a single ._invoke method.\nfunction defineIteratorMethods(prototype){[\"next\",\"throw\",\"return\"].forEach(function(method){define(prototype,method,function(arg){return this._invoke(method,arg);});});}exports.isGeneratorFunction=function(genFun){var ctor=typeof genFun===\"function\"&&genFun.constructor;return ctor?ctor===GeneratorFunction||// For the native GeneratorFunction constructor, the best we can\n// do is to check its .name property.\n(ctor.displayName||ctor.name)===\"GeneratorFunction\":false;};exports.mark=function(genFun){if(Object.setPrototypeOf){Object.setPrototypeOf(genFun,GeneratorFunctionPrototype);}else{genFun.__proto__=GeneratorFunctionPrototype;define(genFun,toStringTagSymbol,\"GeneratorFunction\");}genFun.prototype=Object.create(Gp);return genFun;};// Within the body of any async function, `await x` is transformed to\n// `yield regeneratorRuntime.awrap(x)`, so that the runtime can test\n// `hasOwn.call(value, \"__await\")` to determine if the yielded value is\n// meant to be awaited.\nexports.awrap=function(arg){return{__await:arg};};function AsyncIterator(generator,PromiseImpl){function invoke(method,arg,resolve,reject){var record=tryCatch(generator[method],generator,arg);if(record.type===\"throw\"){reject(record.arg);}else{var result=record.arg;var value=result.value;if(value&&typeof value===\"object\"&&hasOwn.call(value,\"__await\")){return PromiseImpl.resolve(value.__await).then(function(value){invoke(\"next\",value,resolve,reject);},function(err){invoke(\"throw\",err,resolve,reject);});}return PromiseImpl.resolve(value).then(function(unwrapped){// When a yielded Promise is resolved, its final value becomes\n// the .value of the Promise<{value,done}> result for the\n// current iteration.\nresult.value=unwrapped;resolve(result);},function(error){// If a rejected Promise was yielded, throw the rejection back\n// into the async generator function so it can be handled there.\nreturn invoke(\"throw\",error,resolve,reject);});}}var previousPromise;function enqueue(method,arg){function callInvokeWithMethodAndArg(){return new PromiseImpl(function(resolve,reject){invoke(method,arg,resolve,reject);});}return previousPromise=// If enqueue has been called before, then we want to wait until\n// all previous Promises have been resolved before calling invoke,\n// so that results are always delivered in the correct order. If\n// enqueue has not been called before, then it is important to\n// call invoke immediately, without waiting on a callback to fire,\n// so that the async generator function has the opportunity to do\n// any necessary setup in a predictable way. This predictability\n// is why the Promise constructor synchronously invokes its\n// executor callback, and why async functions synchronously\n// execute code before the first await. Since we implement simple\n// async functions in terms of async generators, it is especially\n// important to get this right, even though it requires care.\npreviousPromise?previousPromise.then(callInvokeWithMethodAndArg,// Avoid propagating failures to Promises returned by later\n// invocations of the iterator.\ncallInvokeWithMethodAndArg):callInvokeWithMethodAndArg();}// Define the unified helper method that is used to implement .next,\n// .throw, and .return (see defineIteratorMethods).\nthis._invoke=enqueue;}defineIteratorMethods(AsyncIterator.prototype);define(AsyncIterator.prototype,asyncIteratorSymbol,function(){return this;});exports.AsyncIterator=AsyncIterator;// Note that simple async functions are implemented on top of\n// AsyncIterator objects; they just return a Promise for the value of\n// the final result produced by the iterator.\nexports.async=function(innerFn,outerFn,self,tryLocsList,PromiseImpl){if(PromiseImpl===void 0)PromiseImpl=Promise;var iter=new AsyncIterator(wrap(innerFn,outerFn,self,tryLocsList),PromiseImpl);return exports.isGeneratorFunction(outerFn)?iter// If outerFn is a generator, return the full iterator.\n:iter.next().then(function(result){return result.done?result.value:iter.next();});};function makeInvokeMethod(innerFn,self,context){var state=GenStateSuspendedStart;return function invoke(method,arg){if(state===GenStateExecuting){throw new Error(\"Generator is already running\");}if(state===GenStateCompleted){if(method===\"throw\"){throw arg;}// Be forgiving, per 25.3.3.3.3 of the spec:\n// https://people.mozilla.org/~jorendorff/es6-draft.html#sec-generatorresume\nreturn doneResult();}context.method=method;context.arg=arg;while(true){var delegate=context.delegate;if(delegate){var delegateResult=maybeInvokeDelegate(delegate,context);if(delegateResult){if(delegateResult===ContinueSentinel)continue;return delegateResult;}}if(context.method===\"next\"){// Setting context._sent for legacy support of Babel's\n// function.sent implementation.\ncontext.sent=context._sent=context.arg;}else if(context.method===\"throw\"){if(state===GenStateSuspendedStart){state=GenStateCompleted;throw context.arg;}context.dispatchException(context.arg);}else if(context.method===\"return\"){context.abrupt(\"return\",context.arg);}state=GenStateExecuting;var record=tryCatch(innerFn,self,context);if(record.type===\"normal\"){// If an exception is thrown from innerFn, we leave state ===\n// GenStateExecuting and loop back for another invocation.\nstate=context.done?GenStateCompleted:GenStateSuspendedYield;if(record.arg===ContinueSentinel){continue;}return{value:record.arg,done:context.done};}else if(record.type===\"throw\"){state=GenStateCompleted;// Dispatch the exception by looping back around to the\n// context.dispatchException(context.arg) call above.\ncontext.method=\"throw\";context.arg=record.arg;}}};}// Call delegate.iterator[context.method](context.arg) and handle the\n// result, either by returning a { value, done } result from the\n// delegate iterator, or by modifying context.method and context.arg,\n// setting context.delegate to null, and returning the ContinueSentinel.\nfunction maybeInvokeDelegate(delegate,context){var method=delegate.iterator[context.method];if(method===undefined){// A .throw or .return when the delegate iterator has no .throw\n// method always terminates the yield* loop.\ncontext.delegate=null;if(context.method===\"throw\"){// Note: [\"return\"] must be used for ES3 parsing compatibility.\nif(delegate.iterator[\"return\"]){// If the delegate iterator has a return method, give it a\n// chance to clean up.\ncontext.method=\"return\";context.arg=undefined;maybeInvokeDelegate(delegate,context);if(context.method===\"throw\"){// If maybeInvokeDelegate(context) changed context.method from\n// \"return\" to \"throw\", let that override the TypeError below.\nreturn ContinueSentinel;}}context.method=\"throw\";context.arg=new TypeError(\"The iterator does not provide a 'throw' method\");}return ContinueSentinel;}var record=tryCatch(method,delegate.iterator,context.arg);if(record.type===\"throw\"){context.method=\"throw\";context.arg=record.arg;context.delegate=null;return ContinueSentinel;}var info=record.arg;if(!info){context.method=\"throw\";context.arg=new TypeError(\"iterator result is not an object\");context.delegate=null;return ContinueSentinel;}if(info.done){// Assign the result of the finished delegate to the temporary\n// variable specified by delegate.resultName (see delegateYield).\ncontext[delegate.resultName]=info.value;// Resume execution at the desired location (see delegateYield).\ncontext.next=delegate.nextLoc;// If context.method was \"throw\" but the delegate handled the\n// exception, let the outer generator proceed normally. If\n// context.method was \"next\", forget context.arg since it has been\n// \"consumed\" by the delegate iterator. If context.method was\n// \"return\", allow the original .return call to continue in the\n// outer generator.\nif(context.method!==\"return\"){context.method=\"next\";context.arg=undefined;}}else{// Re-yield the result returned by the delegate method.\nreturn info;}// The delegate iterator is finished, so forget it and continue with\n// the outer generator.\ncontext.delegate=null;return ContinueSentinel;}// Define Generator.prototype.{next,throw,return} in terms of the\n// unified ._invoke helper method.\ndefineIteratorMethods(Gp);define(Gp,toStringTagSymbol,\"Generator\");// A Generator should always return itself as the iterator object when the\n// @@iterator function is called on it. Some browsers' implementations of the\n// iterator prototype chain incorrectly implement this, causing the Generator\n// object to not be returned from this call. This ensures that doesn't happen.\n// See https://github.com/facebook/regenerator/issues/274 for more details.\ndefine(Gp,iteratorSymbol,function(){return this;});define(Gp,\"toString\",function(){return\"[object Generator]\";});function pushTryEntry(locs){var entry={tryLoc:locs[0]};if(1 in locs){entry.catchLoc=locs[1];}if(2 in locs){entry.finallyLoc=locs[2];entry.afterLoc=locs[3];}this.tryEntries.push(entry);}function resetTryEntry(entry){var record=entry.completion||{};record.type=\"normal\";delete record.arg;entry.completion=record;}function Context(tryLocsList){// The root entry object (effectively a try statement without a catch\n// or a finally block) gives us a place to store values thrown from\n// locations where there is no enclosing try statement.\nthis.tryEntries=[{tryLoc:\"root\"}];tryLocsList.forEach(pushTryEntry,this);this.reset(true);}exports.keys=function(object){var keys=[];for(var key in object){keys.push(key);}keys.reverse();// Rather than returning an object with a next method, we keep\n// things simple and return the next function itself.\nreturn function next(){while(keys.length){var key=keys.pop();if(key in object){next.value=key;next.done=false;return next;}}// To avoid creating an additional object, we just hang the .value\n// and .done properties off the next function object itself. This\n// also ensures that the minifier will not anonymize the function.\nnext.done=true;return next;};};function values(iterable){if(iterable){var iteratorMethod=iterable[iteratorSymbol];if(iteratorMethod){return iteratorMethod.call(iterable);}if(typeof iterable.next===\"function\"){return iterable;}if(!isNaN(iterable.length)){var i=-1,next=function next(){while(++i<iterable.length){if(hasOwn.call(iterable,i)){next.value=iterable[i];next.done=false;return next;}}next.value=undefined;next.done=true;return next;};return next.next=next;}}// Return an iterator with no values.\nreturn{next:doneResult};}exports.values=values;function doneResult(){return{value:undefined,done:true};}Context.prototype={constructor:Context,reset:function reset(skipTempReset){this.prev=0;this.next=0;// Resetting context._sent for legacy support of Babel's\n// function.sent implementation.\nthis.sent=this._sent=undefined;this.done=false;this.delegate=null;this.method=\"next\";this.arg=undefined;this.tryEntries.forEach(resetTryEntry);if(!skipTempReset){for(var name in this){// Not sure about the optimal order of these conditions:\nif(name.charAt(0)===\"t\"&&hasOwn.call(this,name)&&!isNaN(+name.slice(1))){this[name]=undefined;}}}},stop:function stop(){this.done=true;var rootEntry=this.tryEntries[0];var rootRecord=rootEntry.completion;if(rootRecord.type===\"throw\"){throw rootRecord.arg;}return this.rval;},dispatchException:function dispatchException(exception){if(this.done){throw exception;}var context=this;function handle(loc,caught){record.type=\"throw\";record.arg=exception;context.next=loc;if(caught){// If the dispatched exception was caught by a catch block,\n// then let that catch block handle the exception normally.\ncontext.method=\"next\";context.arg=undefined;}return!!caught;}for(var i=this.tryEntries.length-1;i>=0;--i){var entry=this.tryEntries[i];var record=entry.completion;if(entry.tryLoc===\"root\"){// Exception thrown outside of any try block that could handle\n// it, so set the completion value of the entire function to\n// throw the exception.\nreturn handle(\"end\");}if(entry.tryLoc<=this.prev){var hasCatch=hasOwn.call(entry,\"catchLoc\");var hasFinally=hasOwn.call(entry,\"finallyLoc\");if(hasCatch&&hasFinally){if(this.prev<entry.catchLoc){return handle(entry.catchLoc,true);}else if(this.prev<entry.finallyLoc){return handle(entry.finallyLoc);}}else if(hasCatch){if(this.prev<entry.catchLoc){return handle(entry.catchLoc,true);}}else if(hasFinally){if(this.prev<entry.finallyLoc){return handle(entry.finallyLoc);}}else{throw new Error(\"try statement without catch or finally\");}}}},abrupt:function abrupt(type,arg){for(var i=this.tryEntries.length-1;i>=0;--i){var entry=this.tryEntries[i];if(entry.tryLoc<=this.prev&&hasOwn.call(entry,\"finallyLoc\")&&this.prev<entry.finallyLoc){var finallyEntry=entry;break;}}if(finallyEntry&&(type===\"break\"||type===\"continue\")&&finallyEntry.tryLoc<=arg&&arg<=finallyEntry.finallyLoc){// Ignore the finally entry if control is not jumping to a\n// location outside the try/catch block.\nfinallyEntry=null;}var record=finallyEntry?finallyEntry.completion:{};record.type=type;record.arg=arg;if(finallyEntry){this.method=\"next\";this.next=finallyEntry.finallyLoc;return ContinueSentinel;}return this.complete(record);},complete:function complete(record,afterLoc){if(record.type===\"throw\"){throw record.arg;}if(record.type===\"break\"||record.type===\"continue\"){this.next=record.arg;}else if(record.type===\"return\"){this.rval=this.arg=record.arg;this.method=\"return\";this.next=\"end\";}else if(record.type===\"normal\"&&afterLoc){this.next=afterLoc;}return ContinueSentinel;},finish:function finish(finallyLoc){for(var i=this.tryEntries.length-1;i>=0;--i){var entry=this.tryEntries[i];if(entry.finallyLoc===finallyLoc){this.complete(entry.completion,entry.afterLoc);resetTryEntry(entry);return ContinueSentinel;}}},\"catch\":function _catch(tryLoc){for(var i=this.tryEntries.length-1;i>=0;--i){var entry=this.tryEntries[i];if(entry.tryLoc===tryLoc){var record=entry.completion;if(record.type===\"throw\"){var thrown=record.arg;resetTryEntry(entry);}return thrown;}}// The context.catch method must only be called with a location\n// argument that corresponds to a known catch block.\nthrow new Error(\"illegal catch attempt\");},delegateYield:function delegateYield(iterable,resultName,nextLoc){this.delegate={iterator:values(iterable),resultName:resultName,nextLoc:nextLoc};if(this.method===\"next\"){// Deliberately forget the last sent value so that we don't\n// accidentally pass it on to the delegate.\nthis.arg=undefined;}return ContinueSentinel;}};// Regardless of whether this script is executing as a CommonJS module\n// or not, return the runtime object so that we can declare the variable\n// regeneratorRuntime in the outer scope, which allows this module to be\n// injected easily by `bin/regenerator --include-runtime script.js`.\nreturn exports;}(// If this script is executing as a CommonJS module, use module.exports\n// as the regeneratorRuntime namespace. Otherwise create a new empty\n// object. Either way, the resulting object will be used to initialize\n// the regeneratorRuntime variable at the top of this file.\ntypeof module===\"object\"?module.exports:{});try{regeneratorRuntime=runtime;}catch(accidentalStrictMode){// This module should not be running in strict mode, so the above\n// assignment should always work unless something is misconfigured. Just\n// in case runtime.js accidentally runs in strict mode, in modern engines\n// we can explicitly access globalThis. In older engines we can escape\n// strict mode using a global Function call. This could conceivably fail\n// if a Content Security Policy forbids using Function, but in that case\n// the proper solution is to fix the accidental strict mode problem. If\n// you've misconfigured your bundler to force strict mode and applied a\n// CSP to forbid Function, and you're not willing to fix either of those\n// problems, please detail your unique predicament in a GitHub issue.\nif(typeof globalThis===\"object\"){globalThis.regeneratorRuntime=runtime;}else{Function(\"r\",\"regeneratorRuntime = r\")(runtime);}}","map":null,"metadata":{},"sourceType":"module"}